# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-16 02:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('number', models.CharField(max_length=12, verbose_name='Номер для связи')),
                ('message', models.TextField(max_length=300, verbose_name='Текст письма')),
                ('date_time', models.DateTimeField(default=datetime.datetime(2017, 4, 16, 2, 35, 18, 284763, tzinfo=utc))),
            ],
            options={
                'verbose_name_plural': 'Письма',
            },
        ),
    ]
