# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-18 10:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 18, 10, 8, 18, 336796, tzinfo=utc)),
        ),
    ]
