# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-18 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20170418_1408'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
