# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-15 23:38
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=60, verbose_name='Адрес URL')),
            ],
            options={
                'verbose_name_plural': 'Категории',
                'verbose_name': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=60, verbose_name='Адрес URL')),
                ('body', models.TextField(max_length=500, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, upload_to='media/news', verbose_name='Изображение')),
                ('date_time', models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('published_date', models.DateTimeField(default=datetime.datetime(2017, 4, 15, 23, 38, 12, 12965, tzinfo=utc), verbose_name='Дата публикации')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name_plural': 'Новости',
                'verbose_name': 'Новость',
                'ordering': ['-published_date'],
            },
        ),
    ]
