# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-15 23:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 15, 23, 38, 31, 642087, tzinfo=utc), verbose_name='Дата публикации'),
        ),
    ]
