# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-16 02:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20170416_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 16, 2, 35, 18, 282763, tzinfo=utc), verbose_name='Дата публикации'),
        ),
    ]
