# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-18 10:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20170416_0635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
        migrations.AlterField(
            model_name='news',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 18, 10, 8, 18, 326796, tzinfo=utc), verbose_name='Дата публикации'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
