# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-18 11:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20170418_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 18, 11, 14, 22, 391366, tzinfo=utc), verbose_name='Дата публикации'),
        ),
    ]
