# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-16 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Заголовок')),
                ('body', models.TextField(max_length=300, verbose_name='Текст')),
                ('image', models.ImageField(upload_to='media/slider', verbose_name='Изображение')),
                ('url', models.CharField(max_length=50, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name_plural': 'Слайдер',
            },
        ),
    ]
