# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-11 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('description', models.TextField(max_length=200, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='media/portfolio')),
            ],
            options={
                'verbose_name_plural': 'Наши работы',
                'verbose_name': 'Наша работа',
            },
        ),
    ]
