# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-15 20:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ['pub_date'], 'verbose_name': 'Наша работа', 'verbose_name_plural': 'Наши работы'},
        ),
        migrations.AddField(
            model_name='images',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 15, 20, 25, 24, 418583, tzinfo=utc)),
        ),
    ]
