# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-15 22:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20170416_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ceiling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('description', models.TextField(max_length=200, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='media/portfolio')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2017, 4, 15, 22, 32, 47, 243062, tzinfo=utc))),
            ],
            options={
                'verbose_name': 'Портфолио потолков',
                'verbose_name_plural': 'Портфолио потолков',
                'ordering': ['pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Jalousie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('description', models.TextField(max_length=200, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='media/portfolio')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2017, 4, 15, 22, 32, 47, 243062, tzinfo=utc))),
            ],
            options={
                'verbose_name': 'Портфолио жалюзей',
                'verbose_name_plural': 'Портфолио жалюзей',
                'ordering': ['pub_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ['pub_date'], 'verbose_name': 'Портфолио окон', 'verbose_name_plural': 'Портфолио окон'},
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/portfolio'),
        ),
        migrations.AlterField(
            model_name='images',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 15, 22, 32, 47, 243062, tzinfo=utc)),
        ),
    ]
