# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-15 23:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20170416_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceiling',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/portfolio', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='ceiling',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 15, 23, 27, 7, 654116, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/portfolio', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='images',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 15, 23, 27, 7, 654116, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='jalousie',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/portfolio', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='jalousie',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 15, 23, 27, 7, 654116, tzinfo=utc)),
        ),
    ]
