# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-15 23:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20170416_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceiling',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 15, 23, 38, 31, 638087, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='images',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 15, 23, 38, 31, 636087, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='jalousie',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 15, 23, 38, 31, 637087, tzinfo=utc)),
        ),
    ]
