# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-16 02:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20170416_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceiling',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 16, 2, 35, 18, 279763, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='images',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 16, 2, 35, 18, 277763, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='jalousie',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 16, 2, 35, 18, 278763, tzinfo=utc)),
        ),
    ]
