# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-18 10:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20170416_0635'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ceiling',
        ),
        migrations.DeleteModel(
            name='Jalousie',
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ['pub_date'], 'verbose_name': 'Портфолио', 'verbose_name_plural': 'Портфолио'},
        ),
        migrations.AlterField(
            model_name='images',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 18, 10, 8, 18, 326796, tzinfo=utc)),
        ),
    ]
